import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {  TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/features/theme/theme-provider";
import { NuqsAdapter } from 'nuqs/adapters/next/app'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component that injects global fonts, theme and app providers around page content.
 *
 * @param children - The page or application content to render inside the theme and TRPC providers.
 * @returns The top-level HTML and body structure containing ThemeProvider, TRPCReactProvider, and the Toaster.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider enableSystem defaultTheme="system" attribute={'class'}disableTransitionOnChange 
        > 
        <TRPCReactProvider>
          <NuqsAdapter> 
        
          {children}
          </NuqsAdapter>
          <Toaster position="top-center" richColors closeButton />
        </TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}